export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CITY_ADMIN = 'CITY_ADMIN',
  FRANCHISE_OWNER = 'FRANCHISE_OWNER',
  VENDOR = 'VENDOR',
  TECHNICIAN = 'TECHNICIAN',
  RIDER = 'RIDER',
  CUSTOMER = 'CUSTOMER',
}
